"""
Rebuild src/data/titleOneSchools.ts from official sources.

  * Which schools are Title I, plus official names and addresses:
    NC DPI School Report Card data set, table rcd_location, column title_i = "Y".
    https://www.dpi.nc.gov/data-reports/school-report-cards/school-report-card-resources-researchers
  * Map coordinates: NCES Common Core of Data school directory, read through the
    Urban Institute Education Data API (joined on the NC school code).

Run once a year when DPI publishes a new School Report Card data set:

    pip install openpyxl
    python3 scripts/build_title_i_schools.py \
        --src-zip "https://www.dpi.nc.gov/src-data-set-2024-252-2/open" --ccd-year 2024

--src-zip is the "part 2 of 2" data set download (it contains rcd_location.xlsx).
--ccd-year is the fall year of the newest CCD directory (2024 = 2024-25).
"""

import argparse
import io
import json
import urllib.request
import zipfile
from pathlib import Path

import openpyxl

DATA = Path(__file__).resolve().parent.parent / "src" / "data"
OUT = DATA / "titleOneSchools.ts"
# Small file so pages that only show the count don't pull in the full list.
SUMMARY = DATA / "titleOneSummary.ts"
# Schools FSA has confirmed as Title I for a newer school year than the latest DPI data set.
# Remove an entry once the DPI data lists the school as Title I on its own.
TITLE_I_OVERRIDES = {
    "920416": "Fuller Elementary (Title I as of 2025-26, confirmed by FSA)",
    "920460": "Kingswood Elementary (Title I as of 2025-26, confirmed by FSA)",
}

TYPE_BY_CATEGORY = {"E": "elementary", "M": "middle", "H": "high", "I": "combined", "A": "combined", "T": "combined"}


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "fsa-site-data-build"})
    with urllib.request.urlopen(req, timeout=600) as resp:
        return resp.read()


def load_src(zip_url: str):
    archive = zipfile.ZipFile(io.BytesIO(fetch(zip_url)))
    name = next(n for n in archive.namelist() if n.endswith("rcd_location.xlsx"))
    sheet = openpyxl.load_workbook(io.BytesIO(archive.read(name)), read_only=True).worksheets[0]
    rows = sheet.iter_rows(values_only=True)
    header = next(rows)
    records = [dict(zip(header, row)) for row in rows]
    year = max(r["year"] for r in records)
    schools = [r for r in records if r["year"] == year and r["agency_level"] == "SCH"]
    return year, schools


def load_ccd(year: int):
    url = f"https://educationdata.urban.org/api/v1/schools/ccd/directory/{year}/?fips=37"
    by_code = {}
    while url:
        page = json.loads(fetch(url))
        for school in page["results"]:
            code = str(school.get("seasch") or "").replace("-", "")[-6:]
            if code and school.get("latitude") and school.get("longitude"):
                by_code[code] = school
        url = page.get("next")
    return by_code


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--src-zip", required=True)
    parser.add_argument("--ccd-year", type=int, required=True)
    args = parser.parse_args()

    src_year, schools = load_src(args.src_zip)
    coords = load_ccd(args.ccd_year)

    out, missing = [], []
    for s in schools:
        if s["title_i"] != "Y" and str(s["agency_code"]) not in TITLE_I_OVERRIDES:
            continue
        ccd = coords.get(str(s["agency_code"]))
        if not ccd:
            missing.append(s["name"])
            continue
        street = " ".join(str(part).strip() for part in (s["street_addr"], s["street_addr2"]) if part and str(part).strip())
        out.append(
            {
                "id": str(s["agency_code"]),
                "name": s["name"].strip(),
                "type": TYPE_BY_CATEGORY.get(s["category_code"], "combined"),
                "grades": s["grade_span"],
                "address": f"{street}, {s['city']}, NC {s['zip']}",
                "county": s["county"],
                "charter": s["designation_Type"] == "C",
                "coordinates": [round(ccd["longitude"], 5), round(ccd["latitude"], 5)],
            }
        )
    out.sort(key=lambda s: (s["county"], s["name"]))

    school_year = f"{src_year - 1}-{str(src_year)[2:]}"
    lines = [
        "// GENERATED by scripts/build_title_i_schools.py. Do not edit by hand.",
        f"// Title I schools in North Carolina, {school_year} school year.",
        "// Title I status, names and addresses: NC DPI School Report Card data (rcd_location.title_i).",
        f"// Coordinates: NCES Common Core of Data school directory ({args.ccd_year}-{str(args.ccd_year + 1)[2:]}).",
        "// Also includes schools confirmed Title I by FSA for a newer year (TITLE_I_OVERRIDES in the script).",
        "",
        'export type SchoolType = "elementary" | "middle" | "high" | "combined";',
        "",
        "export interface School {",
        "  id: string; // NC DPI school code",
        "  name: string;",
        "  type: SchoolType;",
        "  grades: string; // e.g. PK:05",
        "  address: string;",
        "  county: string;",
        "  charter: boolean;",
        "  coordinates: [number, number]; // [longitude, latitude]",
        "}",
        "",
        f'export {{ TITLE_I_SCHOOL_YEAR }} from "./titleOneSummary";',
        "",
        "export const titleOneSchools: School[] = [",
    ]
    lines += [f"  {json.dumps(s, ensure_ascii=False)}," for s in out]
    lines += ["];", ""]
    OUT.write_text("\n".join(lines))
    SUMMARY.write_text(
        "// GENERATED by scripts/build_title_i_schools.py. Do not edit by hand.\n"
        f'export const TITLE_I_SCHOOL_YEAR = "{school_year}";\n'
        f"export const TITLE_I_SCHOOL_COUNT = {len(out)};\n"
    )

    print(f"{school_year}: wrote {len(out)} Title I schools to {OUT}")
    if missing:
        print(f"Skipped {len(missing)} without CCD coordinates: {missing}")


if __name__ == "__main__":
    main()
